pkonly: true
droprate: 0.00
lootingrate: 0.0
clickinfo: false
mobpkonly: true
creeperdroprate: 0.000
zombiedroprate: 0.000
skeletondroprate: 0.000
witherdroprate: 0.000
spiderdroprate: 0.000
endermandroprate: 0.000
blazedroprate: 0.000
horsedroprate: 0.000
squiddroprate: 0.000
silverfishdroprate: 0.000
enderdragondroprate: 0.00
slimedroprate: 0.000
irongolemdroprate: 0.000
mushroomcowdroprate: 0.000
batdroprate: 0.000
pigzombiedroprate: 0.000
snowmandroprate: 0.000
ghastdroprate: 0.000
pigdroprate: 0.000
villagerdroprate: 0.000
sheepdroprate: 0.000
cowdroprate: 0.000
chickendroprate: 0.000
ocelotdroprate: 0.000
witchdroprate: 0.000
magmacubedroprate: 0.000
wolfdroprate: 0.000
cavespiderdroprate: 0.000
fixcase: true
updatecheck: false
broadcast: false
broadcastrange: 1
antideathchest: false
dropboringplayerheads: false